---
language: go
go_import_path: github.com/piotrpersona
before_deploy:
  - ./build.sh
deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file_glob: true
  file: $GOPATH/bin/docku-*
  skip_cleanup: true
  on:
    tags: true
